---
:current_version: 1.0.41
:release_history:
- :version: 1.0.41
  :released_at: 2019-05-14 12:21:40.118549000 -04:00
- :version: 1.0.40
  :released_at: 2019-04-13 01:06:14.003020000 -04:00
- :version: 1.0.39
  :released_at: 2018-03-11 10:45:57.919999000 -04:00
- :version: 1.0.38
  :released_at: 2018-02-10 08:14:59.064309000 -05:00
- :version: 1.0.37
  :released_at: 2018-02-10 07:30:09.518196000 -05:00
- :version: 1.0.36
  :released_at: 2018-02-10 01:16:44.471006000 -05:00
- :version: 1.0.35
  :released_at: 2018-02-10 01:14:53.333572000 -05:00
- :version: 1.0.34
  :released_at: 2017-12-03 19:49:04.969451000 -05:00
- :version: 1.0.33
  :released_at: 2017-11-24 17:34:22.388640000 -05:00
- :version: 1.0.32
  :released_at: 2017-11-24 16:28:12.925488000 -05:00
- :version: 1.0.31
  :released_at: 2017-11-24 16:25:46.052685000 -05:00
- :version: 1.0.30
  :released_at: 2017-11-24 16:15:56.310798000 -05:00
- :version: 1.0.29
  :released_at: 2017-11-24 15:46:31.133939000 -05:00
- :version: 1.0.28
  :released_at: 2017-10-05 15:08:35.484546000 -04:00
- :version: 1.0.27
  :released_at: 2017-10-05 14:50:30.736843000 -04:00
- :version: 1.0.26
  :released_at: 2017-10-05 14:34:14.410991000 -04:00
- :version: 1.0.25
  :released_at: 2017-10-05 14:26:54.144351000 -04:00
- :version: 1.0.24
  :released_at: 2017-09-08 14:01:32.557581000 -04:00
- :version: 1.0.23
  :released_at: 2017-09-08 13:05:48.113217000 -04:00
- :version: 1.0.22
  :released_at: 2017-09-08 13:02:07.513279000 -04:00
- :version: 1.0.21
  :released_at: 2017-09-08 13:02:07.399662000 -04:00
- :version: 1.0.20
  :released_at: 2017-09-08 00:08:39.667155000 -04:00
- :version: 1.0.19
  :released_at: 2017-09-08 00:08:39.531994000 -04:00
- :version: 1.0.18
  :released_at: 2017-09-08 00:04:46.963801000 -04:00
- :version: 1.0.17
  :released_at: 2017-09-08 00:04:46.849962000 -04:00
- :version: 1.0.16
  :released_at: 2017-09-08 00:03:58.018985000 -04:00
- :version: 1.0.15
  :released_at: 2017-09-07 21:06:56.416681000 -04:00
- :version: 1.0.14
  :released_at: 2017-09-07 20:50:38.627149000 -04:00
- :version: 1.0.13
  :released_at: 2017-09-07 20:32:42.145835000 -04:00
- :version: 1.0.12
  :released_at: 2017-09-07 18:57:27.393298000 -04:00
- :version: 1.0.11
  :released_at: 2017-09-07 18:53:26.997083000 -04:00
- :version: 1.0.10
  :released_at: 2017-09-07 18:44:26.737898000 -04:00
- :version: 1.0.9
  :released_at: 2017-09-07 18:40:58.330222000 -04:00
- :version: 1.0.8
  :released_at: 2017-09-07 18:39:14.234395000 -04:00
- :version: 1.0.7
  :released_at: 2017-09-07 18:34:56.006675000 -04:00
- :version: 1.0.6
  :released_at: 2017-09-07 18:34:54.002530000 -04:00
- :version: 1.0.5
  :released_at: 2017-09-07 18:30:41.500626000 -04:00
- :version: 1.0.4
  :released_at: 2017-09-07 18:25:10.628447000 -04:00
- :version: 1.0.3
  :released_at: 2017-09-07 18:22:33.084532000 -04:00
- :version: 1.0.2
  :released_at: 2017-09-07 18:08:58.606758000 -04:00
- :version: 1.0.1
  :released_at: 2017-09-07 17:58:10.945392000 -04:00
- :version: 1.0.0
  :released_at: 2017-09-07 17:15:51.233111000 -04:00
